version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 20-bullseye
    volumes:
      - ..:/workspace:cached
    networks:
      - backend
    environment:
      DATABASE_URL: 'postgresql://postgres:123456@db:5432/mydb'
    ports:
      - '3000:3000'
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
